# Generated by Django 4.2.2 on 2023-06-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_remove_user_updated_user_update_alter_user_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update',
            new_name='updated',
        ),
    ]
