# Generated by Django 4.2.2 on 2023-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_label', '0002_rename_update_post_updated'),
        ('core_user', '0004_rename_update_user_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_label.post'),
        ),
    ]
